version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    ulimits:
      nproc: 4096
      nofile:
         soft: 4096
         hard: 4096
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A app.worker.worker.app worker -P gevent -c 100 --loglevel=warning --purge
    ulimits:
      nproc: 4096
      nofile:
         soft: 4096
         hard: 4096
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    ulimits:
      nproc: 4096
      nofile:
         soft: 65535
         hard: 65535
    image: "redis:alpine"
    ports:
      - "6379:6379"
